server:
  port: 8000

spring:
  datasource:
    name: tms_test_mock
    type: com.alibaba.druid.pool.DruidDataSource

    # druid相关配置
    druid:
      # 监控统计拦截的filters
      filters: stat
      # 连接配置
      url: jdbc:mysql://192.168.108.17:3306/sampledb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 1024
      # 配置初始化大小
      initial-size: 1
      min-idle: 1
      max-active: 20

      # 获取连接等待超时时间
      max-wait: 60000

      # 间隔多久进行一次检测，检测需要关闭的空闲连结
      time-between-eviction-runs-millis: 60000

      # 连接的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'X'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  type-aliases-package: com.hello.tms.mock.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# dubbo相关配置
dubbo:
  application:
    name: tms-dev-dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.hello.tms.dev.provide.service