package com.hello.tms.mock.dao.mapper;

import com.hello.tms.mock.model.TpUser;

public interface TpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated
     */
    int insert(TpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated
     */
    int insertSelective(TpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated
     */
    TpUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tp_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TpUser record);
}